alias mkdir='mkdir -p'
alias top='htop'
alias refresh='source /home/anthony/.bashrc'
alias shutdown='sudo shutdown -h now'
alias restart='sudo reboot now'
alias minecraft='pushd .;cd /media/one/games/minecraft;./start.sh;popd'
alias mntstora='sudo smbmount \\192.168.1.5\FamilyLibrary /media/stora -o username=anton1,password=sel12ti'
alias umntstora='sudo smbumount /media/stora'
alias sed='gsed'
