#!/bin/bash

CLEAR="\033[1;0m"
GREEN="\033[1;32m"
CYAN="\033[1;36m"
BRANCH="$(git branch 2> /dev/null | grep -e '\* ' | sed 's/^..\(.*\)/\1 /')"

echo -e "$GREEN- Starting: merge-branch on $1 to branch '$BRANCH' -$CLEAR"

echo ''
echo -e "$CYAN- Executing: git checkout $1 -$CLEAR"
git checkout $1

echo ''
echo -e "$CYAN- Executing: git fetch origin $1 -$CLEAR"
git fetch origin $1

echo ''
echo -e "$CYAN- Executing: git fast-forward merge (on $1) -$CLEAR"
git merge origin $1

echo ''
echo -e "$CYAN- Executing: git checkout branch -$CLEAR"
git checkout -

echo ''
echo -e "$CYAN- Executing: git fetch (on branch) -$CLEAR"
git fetch origin $BRANCH

echo ''
echo -e "$CYAN- Executing: git fast-foward merge (on branch) -$CLEAR"
git merge origin $BRANCH

echo ''
echo -e "$CYAN- Executing: git merge $1 -$CLEAR"
git merge $1
