#!/bin/bash

CLEAR="\033[1;0m"
GREEN="\033[1;32m"
CYAN="\033[1;36m"

echo -e "$GREEN- Starting: spring-clean -$CLEAR"

echo ''
echo -e "$CYAN- Nuking local branches -$CLEAR"
git branch |
  grep -v "^* " |
  grep -v "/master$" |
  grep -v "^[* ] main$" |
  grep -v "^[* ] production$" |
  grep -v "^[* ] green$" |
  xargs git branch -D

echo ''
echo -e "$CYAN- Nuking remote branches -$CLEAR"
git branch -r |
  grep -v "^* " |
  grep -v "/master$" |
  grep -v "/main$" |
  grep -v "/production$" |
  grep -v "/green$" |
  xargs git branch -D -r


if [ $? -ne 0 ]; then
  echo ''
  echo -e "$CYAN- remote branch nuke failed, manually delete these: -$CLEAR"
  git branch -r | grep \'
fi