#!/bin/bash

CLEAR="\033[1;0m"
GREEN="\033[0;32m"
BRANCH="$(git branch 2> /dev/null | grep -e '\* ' | sed 's/^..\(.*\)/\1 /' | sed -e 's/^ *//g' -e 's/ *$//g')"


echo -e "$GREEN- Starting: merge-main on branch '$BRANCH' -$CLEAR"

echo $'\nExecuting: git checkout main'
git checkout main

echo $'\nExecuting: git pull (on main)'
git pull

echo $'\nExecuting: git fetch (on main)'
git fetch

echo $'\nExecuting: git checkout branch'
git checkout $BRANCH

echo $'\nExecuting: git pull (on branch)'
git pull

echo $'\nExecuting: git merge main'
git merge main
