#!/bin/bash

CLEAR="\033[1;0m"
GREEN="\033[1;32m"
CYAN="\033[1;36m"
BRANCH="$(git branch 2> /dev/null | grep -e '\* ' | sed 's/^..\(.*\)/\1 /')"

echo -e "$GREEN- Starting: rebase-branch on '$1' to '$BRANCH' -$CLEAR"

echo ''
echo -e "$CYAN- Executing: git checkout $1 -$CLEAR"
git checkout $1

echo ''
echo -e "$CYAN- Executing: git update-branch (on '$1') -$CLEAR"
git update-branch

echo ''
echo -e "$CYAN- Executing: git checkout branch -$CLEAR"
git checkout -

echo ''
echo -e "$CYAN- Executing: git update-branch (on '$BRANCH') -$CLEAR"
git update-branch

echo ''
echo -e "$CYAN- Executing: git rebase $1 -$CLEAR"
git rebase $1
