# Common apps installed on all platforms.
# Columns: name   apt-name   flatpak-id
# Use '-' to mark a column as not applicable for that platform.

# cli tools
bats-core           bats              -
direnv              direnv            -
fzf                 fzf               -
gh                  gh                -
jq                  jq                -
mas                 -                 -
ncdu                ncdu              -
the_silver_searcher silversearcher-ag -
watch               procps            -
zoxide              zoxide            -


# gui apps
affinity-designer   -                 -
brave-browser       -                 com.brave.Browser
canva               -                 -
firefox             -                 org.mozilla.firefox
font-fira-code      fonts-fira-code   -
huiontablet         -                 -
imageoptim          -                 -
iterm2              -                 -
kensingtonworks     -                 -
licecap             -                 -
macdown             -                 -
obsidian            -                 md.obsidian.Obsidian
raycast             -                 -
slack               slack             com.slack.Slack
steam               steam             -
visual-studio-code  code              com.visualstudio.code
wave                -                 -
