# Personal mode apps.
# Columns: name   apt-name   flatpak-id

# cli tools
bitwarden-cli         bitwarden-cli     -
coreutils             -                 -
ente-cli              ente-cli          -


# gui apps
bambu-studio          -                 com.bambulab.BambuStudio
bitwarden             -                 com.bitwarden.desktop
calibre               calibre           com.calibre_ebook.calibre
coconutbattery        -                 -
cyberduck             -                 ch.cyberduck.Cyberduck
discord               -                 com.discordapp.Discord
drivethrurpg          -                 -
ente-auth             -                 io.ente.auth
gimp                  gimp              org.gimp.GIMP
home-assistant        -                 -
jellyfin-media-player -                 com.github.iwalton3.jellyfin-media-player
keymapp               -                 -
krita                 krita             org.kde.krita
openemu               -                 -
sequel-ace            -                 -
signal                signal-desktop    org.signal.Signal
sigil                 sigil             com.sigil_ebook.Sigil
sourcetree            -                 -
synology-drive        -                 -
transmission          transmission-gtk  org.transmissionbt.Transmission
vlc                   vlc               org.videolan.VLC