# Work mode apps.
# Columns: name   apt-name   flatpak-id

# cli tools
1password-cli       1password-cli   -
watchman            watchman        -


# gui apps
hiddenbar           -               -
meetingbar          -               -
